insert into users(id, name, email, city) values (1, "Amy Henderson", "ahenderson@gmail.com", "Oklahoma City");
insert into users(id, name, email, city) values (2, "Amy Murphy", "amurphy@outlook.com", "Minneapolis");
insert into users(id, name, email, city) values (3, "Amy Clark", "aclark@yahoo.com", "St. Louis");
insert into users(id, name, email, city) values (4, "Amy Ramirez", "aramirez@gmail.com", "Denver");
insert into users(id, name, email, city) values (5, "Amy Roberts", "aroberts@outlook.com", "Springfield");
insert into users(id, name, email, city) values (6, "Amy Richardson", "arichardson@netgloo.com", "Miami");
insert into users(id, name, email, city) values (7, "Amy Bailey", "abailey@gmail.com", "San Jose");
insert into users(id, name, email, city) values (8, "Stephanie Moore", "smoore@outlook.com", "San Antonio");
insert into users(id, name, email, city) values (9, "Stephanie Robinson", "srobinson@yahoo.com", "Oklahoma City");
insert into users(id, name, email, city) values (10, "Stephanie Kelly", "skelly@gmail.com", "Minneapolis");
insert into users(id, name, email, city) values (11, "Stephanie James", "sjames@outlook.com", "St. Louis");
insert into users(id, name, email, city) values (12, "Stephanie Wright", "swright@yahoo.com", "Denver");
insert into users(id, name, email, city) values (13, "Stephanie Garcia", "sgarcia@gmail.com", "Springfield");
insert into users(id, name, email, city) values (14, "Stephanie Foster", "sfoster@outlook.com", "Miami");
insert into users(id, name, email, city) values (15, "Nancy Foster", "nfoster@yahoo.com", "San Jose");
insert into users(id, name, email, city) values (16, "Martha Foster", "mfoster@gmail.com", "San Antonio");
insert into users(id, name, email, city) values (17, "Eugene Foster", "efoster@outlook.com", "Oklahoma City");
insert into users(id, name, email, city) values (18, "Jonathan Foster", "jfoster@yahoo.com", "Minneapolis");
insert into users(id, name, email, city) values (19, "Jonathan Harris", "jharris@gmail.com", "St. Louis");
insert into users(id, name, email, city) values (20, "Jonathan Ross", "jross@outlook.com", "Denver");
insert into users(id, name, email, city) values (21, "Jonathan Johnson", "jjohnson@yahoo.com", "Springfield");
insert into users(id, name, email, city) values (22, "Jonathan Green", "jgreen@gmail.com", "Miami");
insert into users(id, name, email, city) values (23, "Jonathan Lee", "jlee@outlook.com", "San Jose");
insert into users(id, name, email, city) values (24, "Jonathan Gonzales", "jgonzales@yahoo.com", "San Antonio");
insert into users(id, name, email, city) values (25, "Maria Gonzales", "mgonzales@gmail.com", "Oklahoma City");
insert into users(id, name, email, city) values (26, "Jessica Gonzales", "jgonzales@outlook.com", "Minneapolis");
insert into users(id, name, email, city) values (27, "Andrew Gonzales", "agonzales@yahoo.com", "St. Louis");
insert into users(id, name, email, city) values (28, "Sean Gonzales", "sgonzales@gmail.com", "Denver");
insert into users(id, name, email, city) values (29, "Earl Gonzales", "egonzales@outlook.com", "Springfield");
insert into users(id, name, email, city) values (30, "Earl Diaz", "ediaz@yahoo.com", "Miami");
insert into users(id, name, email, city) values (31, "Earl Rivera", "erivera@gmail.com", "San Jose");
insert into users(id, name, email, city) values (32, "Earl Davis", "edavis@outlook.com", "San Antonio");
insert into users(id, name, email, city) values (33, "Earl Price", "eprice@yahoo.com", "Oklahoma City");
insert into users(id, name, email, city) values (34, "Earl Rogers", "erogers@gmail.com", "Minneapolis");
insert into users(id, name, email, city) values (35, "Earl Sanchez", "esanchez@outlook.com", "St. Louis");
insert into users(id, name, email, city) values (36, "Earl Alexander", "ealexander@yahoo.com", "Denver");
insert into users(id, name, email, city) values (37, "Earl Butler", "ebutler@gmail.com", "Springfield");
insert into users(id, name, email, city) values (38, "Denise Watson", "dwatson@outlook.com", "Miami");
insert into users(id, name, email, city) values (39, "Ronald Russell", "rrussell@yahoo.com", "San Jose");
insert into users(id, name, email, city) values (40, "Raymond Gonzalez", "rgonzalez@gmail.com", "San Antonio");
insert into users(id, name, email, city) values (41, "Gary Cooper", "gcooper@outlook.com", "Oklahoma City");
insert into users(id, name, email, city) values (42, "Gary Lopez", "glopez@yahoo.com", "Minneapolis");
insert into users(id, name, email, city) values (43, "Gary Powell", "gpowell@gmail.com", "St. Louis");
insert into users(id, name, email, city) values (44, "Gary Martin", "gmartin@outlook.com", "Denver");
insert into users(id, name, email, city) values (45, "Gary Simmons", "gsimmons@yahoo.com", "Springfield");
insert into users(id, name, email, city) values (46, "Gary Jenkins", "gjenkins@gmail.com", "Miami");
insert into users(id, name, email, city) values (47, "Gary Morgan", "gmorgan@outlook.com", "San Jose");
insert into users(id, name, email, city) values (48, "Gary Howard", "ghoward@yahoo.com", "San Antonio");
insert into users(id, name, email, city) values (49, "Albert Howard", "ahoward@gmail.com", "Oklahoma City");
insert into users(id, name, email, city) values (50, "Kathy Howard", "kathy.howard@outlook.com", "Minneapolis");
insert into users(id, name, email, city) values (51, "Jeffrey Howard", "jeffrey.howard@yahoo.com", "St. Louis");
insert into users(id, name, email, city) values (52, "Ernest Howard", "ernest.howard@gmail.com", "Denver");
insert into users(id, name, email, city) values (53, "Joshua Cook", "joshua.cook@outlook.com", "Springfield");
insert into users(id, name, email, city) values (54, "Jeremy Hughes", "jeremy.hughes@yahoo.com", "Miami");
insert into users(id, name, email, city) values (55, "Jeremy Sanders", "jeremy.sanders@gmail.com", "San Jose");
insert into users(id, name, email, city) values (56, "Jeremy Thomas", "jeremy.thomas@outlook.com", "San Antonio");
insert into users(id, name, email, city) values (57, "Jeremy Turner", "jeremy.turner@yahoo.com", "Oklahoma City");
insert into users(id, name, email, city) values (58, "Jeremy Campbell", "jeremy.campbell@gmail.com", "Minneapolis");
insert into users(id, name, email, city) values (59, "Jeremy Williams", "jeremy.williams@outlook.com", "St. Louis");
insert into users(id, name, email, city) values (60, "Ryan Hall", "ryan.hall@yahoo.com", "Denver");
insert into users(id, name, email, city) values (61, "Norma Nelson", "norma.nelson@gmail.com", "Springfield");
insert into users(id, name, email, city) values (62, "Jane Brown", "jane.brown@outlook.com", "Miami");
insert into users(id, name, email, city) values (63, "Beverly Walker", "beverly.walker@yahoo.com", "San Jose");
insert into users(id, name, email, city) values (64, "Paula Phillips", "paula.phillips@gmail.com", "San Antonio");
insert into users(id, name, email, city) values (65, "Carlos Brooks", "carlos.brooks@outlook.com", "Oklahoma City");
insert into users(id, name, email, city) values (66, "Katherine Bell", "katherine.bell@yahoo.com", "Minneapolis");
insert into users(id, name, email, city) values (67, "Kelly Thompson", "kelly.thompson@gmail.com", "St. Louis");
insert into users(id, name, email, city) values (68, "Samuel Morris", "samuel.morris@outlook.com", "Denver");
insert into users(id, name, email, city) values (69, "Wayne King", "wayne.king@yahoo.com", "Springfield");
insert into users(id, name, email, city) values (70, "Wayne Gray", "wayne.gray@gmail.com", "Miami");
insert into users(id, name, email, city) values (71, "Wayne Stewart", "wayne.stewart@outlook.com", "San Jose");
insert into users(id, name, email, city) values (72, "Wayne Carter", "wayne.carter@yahoo.com", "San Antonio");
insert into users(id, name, email, city) values (73, "Wayne Reed", "wayne.reed@gmail.com", "Oklahoma City");
insert into users(id, name, email, city) values (74, "Wayne Scott", "wayne.scott@outlook.com", "Minneapolis");
insert into users(id, name, email, city) values (75, "Peter Evans", "peter.evans@yahoo.com", "St. Louis");
insert into users(id, name, email, city) values (76, "Victor Collins", "victor.collins@gmail.com", "Denver");
insert into users(id, name, email, city) values (77, "Elizabeth Perry", "elizabeth.perry@outlook.com", "Springfield");
insert into users(id, name, email, city) values (78, "Janet Wood", "janet.wood@yahoo.com", "Miami");
insert into users(id, name, email, city) values (79, "Alice Miller", "alice.miller@gmail.com", "San Jose");
insert into users(id, name, email, city) values (80, "Alice Anderson", "alice.anderson@outlook.com", "San Antonio");
insert into users(id, name, email, city) values (81, "Alice Hill", "alice.hill@yahoo.com", "Oklahoma City");
insert into users(id, name, email, city) values (82, "Alice Washington", "alice.washington@gmail.com", "Minneapolis");
insert into users(id, name, email, city) values (83, "Alice White", "alice.white@outlook.com", "St. Louis");
insert into users(id, name, email, city) values (84, "Alice Mitchell", "alice.mitchell@yahoo.com", "Denver");
insert into users(id, name, email, city) values (85, "Alice Bryant", "alice.bryant@gmail.com", "Springfield");
insert into users(id, name, email, city) values (86, "Alice Collins", "alice.collins@gmail.com", "San Francisco");
insert into users(id, name, email, city) values (87, "David Baker", "david.baker@yahoo.com", "San Jose");
insert into users(id, name, email, city) values (88, "Ruth Baker", "ruth.baker@gmail.com", "San Antonio");
insert into users(id, name, email, city) values (89, "Teresa Baker", "teresa.baker@outlook.com", "Oklahoma City");
insert into users(id, name, email, city) values (90, "Theresa Wilson", "theresa.wilson@yahoo.com", "Minneapolis");
insert into users(id, name, email, city) values (91, "Robert Parker", "robert.parker@gmail.com", "St. Louis");
insert into users(id, name, email, city) values (92, "Robert Adams", "robert.adams@outlook.com", "Denver");
insert into users(id, name, email, city) values (93, "Robert Perez", "robert.perez@yahoo.com", "Springfield");
insert into users(id, name, email, city) values (94, "Robert Griffin", "robert.griffin@gmail.com", "Miami");
insert into users(id, name, email, city) values (95, "Robert Long", "robert.long@outlook.com", "San Jose");
insert into users(id, name, email, city) values (96, "Robert Ward", "robert.ward@yahoo.com", "San Antonio");
insert into users(id, name, email, city) values (97, "Robert Allen", "robert.allen@gmail.com", "Oklahoma City");
insert into users(id, name, email, city) values (98, "Robert Edwards", "robert.edwards@outlook.com", "Minneapolis");
insert into users(id, name, email, city) values (99, "Robert Young", "robert.young@yahoo.com", "St. Louis");
insert into users(id, name, email, city) values (100, "Robert Green", "robert.green@gmail.com", "Denver");
